# for dev only
spring.thymeleaf.cache=false

spring.application.name=movierating

# === Database Config ===
spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:54592/railway
spring.datasource.username=postgres
spring.datasource.password=OpMMSxPgYpJgLzWgsjUIEPOxkrtPNusD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Logging ===
logging.level.org.springframework=INFO
logging.level.com.backbase=DEBUG

# === Swagger/OpenAPI ===
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# === OMDB API (replace with real key) ===
omdb.api.key=ac0264bb

# spring.security.user.name=admin
# spring.security.user.password=admin123

